# Generated by Django 4.0 on 2021-12-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_user',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Id User'),
        ),
    ]
