# Generated by Django 4.0 on 2021-12-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_num', models.IntegerField(unique=True, verbose_name='Booking Number')),
                ('loading_port', models.CharField(max_length=50, verbose_name='Loading port')),
                ('discharge_port', models.CharField(max_length=50, verbose_name='Discharge port')),
                ('ship_arr_date', models.DateField(verbose_name='Ship arrival date')),
                ('ship_dep_date', models.DateField(verbose_name='Ship departure date')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.IntegerField(unique=True, verbose_name='Vehicle Identification Number')),
                ('make', models.CharField(max_length=50, verbose_name='Make')),
                ('model', models.IntegerField(verbose_name='Model')),
                ('weight', models.IntegerField(verbose_name='Weight')),
            ],
        ),
    ]
