# Generated by Django 4.0 on 2021-12-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_remove_vehicle_booking_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.vehicle', unique=True),
        ),
    ]
